# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0010_auto_20180612_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_open_for_orders',
            field=models.BooleanField(default=True),
        ),
    ]
