# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-08 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0011_restaurant_is_open_for_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtaskerapp.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='modifier',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='foodtaskerapp.Modifier'),
        ),
    ]
